server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hbl_auth?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
